module.exports = {
    user: {
        findByName: 'select * from user where name = ?',
        insert: 'insert user set ?',
        findByOpenId: 'select * from user where openid = ?',
        findById: 'select * from user where id = ?',
        update: 'update user set ? where id = ?',
        updateByName: 'update user set ? where name = ?',
        findByIds: 'select id, nickName, headPic,signature, createDate from user where id in (?)'
    },
    project: {
        findPageSetting: 'select * from projectPageSetting where pid = ?',
        deleteComment: 'update projectComment set removed = 1 where pid=? and id = ?',
        addNewsLiker: 'insert projectNewsLiker set ?',
        updateNews: 'update projectNews set ? where id = ?',
        deleteNewsComment: 'update projectNewsComment set removed = 1 where pid= ? and newsId=? and id = ?',
        findNewsComments: 'select * from projectNewsComment where pid = ? and newsId=? order by createDate desc',
        findNewsLikers: 'select * from projectNewsLiker where pid = ? and newsId=? order by createDate desc',
        addNews: 'insert projectNews set ?',
        findNews: 'select * from projectNews where pid = ?',
        deleteNews: 'delete from projectNews where pid=? and  id  = ?',
        findCategories: 'select id, name, pid from projectCategory limit ? ,?',
        findBusinessInfo: 'select id, title, shortDesc,`desc`, image, video,`group`,`type`, sortIndex FROM projectBusinessInfo where pid = ? order by sortIndex',
        findTeamStrengths: 'select id, content,`group`, sortIndex, image FROM projectTeamStrength where pid = ? order by sortIndex',
        findById: 'select * from project where id = ?',
        findMemberInfo: 'select id, `name`, image, position, email,createDate, `desc`,`group`, headPic, sortIndex FROM projectMemberInfo where pid = ? order by sortIndex',
        findLikers: 'select id,uid,nickName,headPic, createDate from projectLiker where pid = ?',
        findTags: 'select id, name from tag limit ?, ?',
        findByCreator: 'select * from project where creator = ? limit ?, ?',
        findMusicLib: 'select * from musicLib ',
        findLikersBy: 'select * from projectLiker where pid=? and uid=?',
        findNewsLikersBy: 'select * from projectNewsLiker where pid=? and newsId = ? and uid=?',
        findLikeredProjesctsBy: 'select p.id,p.`name`,p.logo, p.shortDesc, p.commentCount, p.likerCount,creatorHeadPic, creator,creatorNickName from projectLiker l left JOIN project p on l.pid = p.id where l.uid=?',
        insert: 'insert project set ?',
        insertComplaint: 'insert projectComplaint set ?',
        insertPrivateMessage: 'insert projectPrivateMessage set ?',
        find: 'select * from project limit ?,?',
        update: 'update project set ? where id = ?',
        delete: 'delete from project where id = ?',
        findByUid: 'select * from project where creator = ? order by createDate desc',
        addLiker: 'insert projectLiker set ?',
        addComment: 'insert projectComment set ?',
        addNewsComment: 'insert projectNewsComment set ?',
        deleteLiker: 'delete from projectLiker where uid=? and pid = ?',
        deleteNewsLiker: 'delete from projectNewsLiker where uid=? and pid = ? and newsId = ?',
        insertTeamMember: 'insert projectMemberInfo set ?',
        deleteTeamMember: 'delete from projectMemberInfo where id = ?',
        updateTeamMember: 'update projectMemberInfo set ? where id = ?',
        insertPageSetting: 'insert projectPageSetting set ?',
        updatePageSetting: 'update projectPageSetting set ? where id = ? ',
        insertBusinessInfo: 'insert projectBusinessInfo set ?',
        updateBusinessInfo: 'update projectBusinessInfo set ? where id = ?',
        deleteBusinessInfo: 'delete from projectBusinessInfo where id = ?',
        insertTeamStrength: 'insert projectTeamStrength set ?',
        findLikersByUid: 'select headPic, nickName, pid, pName as projectName, createDate from projectLiker l where pid in (select id from project p where creator = ? ) order by createDate desc limit ?,?',
        findLikersForProjectsBy: 'select distinct uid, nickName, headPic, (select count(*) from project where creator = uid) as projectCount from projectLiker where ',
        updateTeamStrength: 'update projectTeamStrength set ? where id = ?',
        deleteTeamStrength: 'delete from projectTeamStrength where id = ?',
        findComments: 'select id, nickName, headPic, content, createDate from projectComment where pid=? order by createDate desc limit ?, ?',
        findCommentProjectBy: 'select c.id, c.content,c.createDate, p.`name`, p.creator, p.creatorNickName,p.creatorHeadPic, p.shortDesc, p.`desc`, p.logo from projectComment c left JOIN project p on p.id = c.pid where c.uid = ? '
    }
}
